### ISSUE TITLE
Solve  "Internal server error: No "exports" main defined"

### ISSUE THREAD

**Issue by linzeguang** [pd4d10/vite-plugin-svgr#45] opened 2022-07-20 10:01 UTC
应该是@svgr/core版本更新到6.3.0引发的问题
我目前的解决方式是在package.json中添加：
`
"resolutions": {
    "@svgr/core": "6.2.1"
  }
`

English is not very good, so I can only answer in Chinese

**Comment by pd4d10** [comment] 2022-07-22 15:47
Duplicate of #46

**Closed by pd4d10** 2022-07-22 15:47 UTC
